---
- hosts: localhost
  gather_facts: no
  connection: local

  vars:
    should_fail_via_fail: true
    should_fail_via_assert: false
    should_fail_via_complex_assert: false

  tasks:
    - name: Fail if conditions warant a failure.
      fail: 
        msg: "There was an epic fail of epic proportions."
      when: should_fail_via_fail

    - name: Stop playbook if an assertation fails.
      assert:
        that: should_fail_via_assert != true

    - name: Assertions can have contain conditions.
      assert:
        that:
          - should_fail_via_fail != true
          - should_fail_via_complex_assert != true
          - should_fail_via_assert != true
