--- 
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - shell: uptime
      register: system_uptime

    - name: Print the registerd output of the 'uptime' command.
      debug:
        var: system_uptime.stdout